### PR TITLE
Refactor and fixed API

### PR DESCRIPTION
**Pull request by ThexXTURBOXx**
"isVerified" and "partners" were wrong type

### CODE REVIEW

**Comment by vinceh121** [comment]
Why did you set the getters in the *Datapoint classes to the package access level?

**Comment by ThexXTURBOXx** [comment]
Those are interfaces. You don't ever need any visibility modifiers in interface classes.
When you implement interfaces, you specify them in the implementing class

**Comment by vinceh121** [comment]
Okay I'll convert those to classes later then cause I messed that up.


And thanks for the correction about the types and refactoring

**Comment by vinceh121** [comment]
Okay I'll convert those to classes later then cause I messed that up.


And thanks for the correction about the types and refactoring

**Comment by ThexXTURBOXx** [comment]
Perfect! You're welcome

**Comment by ThexXTURBOXx** [comment]
Oh, and I just noticed...
I suggest you to take a look at https://projectlombok.org/
For APIs like this one, it's a very useful tool!
E.g. [the class YTStats](https://github.com/vinceh121/socialblade-api/blob/master/src/main/java/me/vinceh121/socialbladeapi/youtube/YTStats.java) could look like [this](https://gist.github.com/ThexXTURBOXx/9589bc6f650f8bec21120269a21532f7) then.
It makes work really easier ;)

**Comment by vinceh121** [comment]
Oh, that's an interesting framework, but I still prefer the old school way...

**Pull request merged**
